apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color
  namespace: argocd
spec:
  project: default
   
  source:
    repoURL: https://github.com/Thiago-Sorrilha/web_color.git
    targetRevision: HEAD
    path: App
  destination:
    server: https://kubernetes.default.svc
    namespace: web-color
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true # mantem o que esta no repo. subscreve qualquer alteracao
      prune: true