apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas:  4
  selector: 
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - name: site
        image: fabricioveronez/web-page:blue
        ports:
        - containerPort: 80
