apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas:  3
  selector: 
    matchLabels:
      app: web-color
  template:
    metadata:
      labels:
        app: web-color
    spec:
      containers:
      - name: site
        image: tpbsdocker/web-page-blue
        ports:
        - containerPort: 80
