apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 5 
  selector: 
    matchLabels:
      app: web_color
  template:
    metadata:
      labels:
        app: web_color
    spec:
      containers:
      - name: site
        image: fabricioveronez/web-page:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-color
spec:
  selector: 
    app: web_color # indica quais os pods alvo referenciados pela label.
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8099
      #nodePort: 30003 # força a porta a usar
  #type: ClusterIP
  type: LoadBalancer # seleciona o tipo de service que sera usado
  